#!/usr/bin/env python3
import sys
import os
import re

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 search_docs.py <search_query>")
        sys.exit(1)
        
    query = sys.argv[1].lower()
    keywords = query.split()
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    docs_path = os.path.join(script_dir, "..", "references", "drizzle-orm-docs.md")
    
    if not os.path.exists(docs_path):
        print(f"Error: Documentation file not found at {docs_path}")
        sys.exit(1)
        
    with open(docs_path, 'r', encoding='utf-8') as f:
        content = f.read()
        
    # Split by the "## Source: " tag generated by the crawler
    sections = content.split("## Source: ")
    
    results = []
    
    for section in sections[1:]: # Skip the first part before the first source
        if not section.strip():
            continue
            
        lines = section.split('\n')
        source_url = lines[0].strip()
        body = '\n'.join(lines[1:])
        
        # Simple scoring based on keyword frequency
        score = 0
        body_lower = body.lower()
        
        for kw in keywords:
            score += body_lower.count(kw)
            
        if score > 0:
            results.append({
                'source': source_url,
                'score': score,
                'snippet': body[:1000] + ("..." if len(body) > 1000 else "")
            })
            
    # Sort by score descending
    results.sort(key=lambda x: x['score'], reverse=True)
    
    top_results = results[:3]
    
    if not top_results:
        print(f"No results found for query: '{query}'")
        sys.exit(0)
        
    print(f"Found {len(results)} matches. Showing top {len(top_results)} results:\n")
    print("=" * 80)
    
    for i, res in enumerate(top_results, 1):
        print(f"RESULT {i} - SOURCE: {res['source']} (Score: {res['score']})")
        print("-" * 80)
        # Extract snippets around the keywords instead of just the first 1000 chars if possible
        # For simplicity, just showing the first 1500 chars which usually contains the intro or relevant code
        snippet = res['snippet'][:1500]
        print(snippet)
        print("=" * 80 + "\n")

if __name__ == "__main__":
    main()
